In [3]:
"""
04-1. 로지스틱 회귀
"""

'\n04-1. 로지스틱 회귀\n'

In [4]:
"""
데이터 가져오기.
"""

import pandas as pd

fish = pd.read_csv("https://bit.ly/fish_csv_data")
fish.head()

Species  Weight  Length  Diagonal   Height   Width
0   Bream   242.0    25.4      30.0  11.5200  4.0200
1   Bream   290.0    26.3      31.2  12.4800  4.3056
2   Bream   340.0    26.5      31.1  12.3778  4.6961
3   Bream   363.0    29.0      33.5  12.7300  4.4555
4   Bream   430.0    29.0      34.0  12.4440  5.1340

In [41]:
"""
DataFrame 데이터를 Numpy 배열로 변환하기.
"""

species = pd.unique(fish["Species"])
print("species_type: ", type(species))
print("species: ", species)

fish_weight_series = fish["Weight"]
print("fish_weight_series_type: ", type(fish_weight_series))

fish_input_df = fish[["Weight", "Length", "Diagonal", "Height", "Width"]]
print("fish_input_df: ", type(fish_input_df))

fish_input = fish_input_df.to_numpy()
print("fish_input: ", type(fish_input))

print("fish_input[:5]: ", fish_input[:5])

fish_target = fish["Species"].to_numpy()
print("fish_target_type: ", type(fish_target))
print("fish_target[:5]:" , fish_target[:5])

print("fish_input.shape:" , fish_input.shape)
print("fish_target.shape:" , fish_target.shape)

species_type:  <class 'numpy.ndarray'>
species:  ['Bream' 'Roach' 'Whitefish' 'Parkki' 'Perch' 'Pike' 'Smelt']
fish_weight_series_type:  <class 'pandas.core.series.Series'>
fish_input_df:  <class 'pandas.core.frame.DataFrame'>
fish_input:  <class 'numpy.ndarray'>
fish_input[:5]:  [[242.      25.4     30.      11.52     4.02  ]
 [290.      26.3     31.2     12.48     4.3056]
 [340.      26.5     31.1     12.3778   4.6961]
 [363.      29.      33.5     12.73     4.4555]
 [430.      29.      34.      12.444    5.134 ]]
fish_target_type:  <class 'numpy.ndarray'>
fish_target[:5]: ['Bream' 'Bream' 'Bream' 'Bream' 'Bream']
fish_input.shape: (159, 5)
fish_target.shape: (159,)


In [22]:
"""
훈련용과 테스트용 데이터로 분리하기
"""

from sklearn.model_selection import train_test_split

train_input, test_input, train_target, test_target = train_test_split(fish_input, fish_target, random_state=42)

print("fish_input.shape:" , fish_input.shape)
print("fish_target.shape:" , fish_target.shape)
print("train_input.shape: ", train_input.shape)
print("train_target.shape: ", train_target.shape)
print("test_input.shape: ", test_input.shape)
print("test_target.shape: ", test_target.shape)

fish_input.shape: (159, 5)
fish_target.shape: (159,)
train_input.shape:  (119, 5)
train_target.shape:  (119,)
test_input.shape:  (40, 5)
test_target.shape:  (40,)


In [25]:
"""
표준화 전처리하기
"""

from sklearn.preprocessing import StandardScaler

ss = StandardScaler()
ss.fit(train_input)
train_scaled = ss.transform(train_input)
test_scaled = ss.transform(test_input)

print("train_scaled[:5]: ", train_scaled[:5])
print("test_scaled[:5]: ", test_scaled[:5])

train_scaled[:5]:  [[ 0.91965782  0.60943175  0.81041221  1.85194896  1.00075672]
 [ 0.30041219  1.54653445  1.45316551 -0.46981663  0.27291745]
 [-1.0858536  -1.68646987 -1.70848587 -1.70159849 -2.0044758 ]
 [-0.79734143 -0.60880176 -0.67486907 -0.82480589 -0.27631471]
 [-0.71289885 -0.73062511 -0.70092664 -0.0802298  -0.7033869 ]]
test_scaled[:5]:  [[-0.88741352 -0.91804565 -1.03098914 -0.90464451 -0.80762518]
 [-1.06924656 -1.50842035 -1.54345461 -1.58849582 -1.93803151]
 [-0.54401367  0.35641402  0.30663259 -0.8135697  -0.65388895]
 [-0.34698097 -0.23396068 -0.22320459 -0.11905019 -0.12233464]
 [-0.68475132 -0.51509149 -0.58801052 -0.8998784  -0.50124996]]


In [43]:

from sklearn.neighbors import KNeighborsClassifier

kn = KNeighborsClassifier(n_neighbors=3)
kn.fit(train_scaled, train_target)

print("kn_train_score: ", kn.score(train_scaled, train_target))  # 0.890
print("kn_scale_score: ", kn.score(test_scaled, test_target))  # 0.850

print("kn.predict(train_scaled[:5]): ", kn.predict(train_scaled[:5]))
print("kn.predict(test_scaled[:5]): ", kn.predict(test_scaled[:5]))

kn_train_score:  0.8907563025210085
kn_scale_score:  0.85
kn.predict(train_scaled[:5]):  ['Bream' 'Pike' 'Smelt' 'Perch' 'Parkki']
kn.predict(test_scaled[:5]):  ['Perch' 'Smelt' 'Pike' 'Perch' 'Perch']


In [68]:
"""
k-이웃인접분류기로 분류된 포인트의 Species 확률
"""
import numpy as np

print("np.unique(fish_target): ", np.unique(fish_target))
proba = kn.predict_proba(test_scaled[:5])
proba_rounded = np.round(proba, decimals=4)
print("proba_rounded:\n", proba_rounded)

distances, indexes = kn.kneighbors(test_scaled[3:4])
print("distances: ", distances)
print("indexes: ", indexes)
print("fish_target[indexes]: ", train_target[indexes])

np.unique(fish_target):  ['Bream' 'Parkki' 'Perch' 'Pike' 'Roach' 'Smelt' 'Whitefish']
proba_rounded:
 [[0.     0.     1.     0.     0.     0.     0.    ]
 [0.     0.     0.     0.     0.     1.     0.    ]
 [0.     0.     0.     1.     0.     0.     0.    ]
 [0.     0.     0.6667 0.     0.3333 0.     0.    ]
 [0.     0.     0.6667 0.     0.3333 0.     0.    ]]


ValueError: Expected 2D array, got 1D array instead:
array=[-0.34698097 -0.23396068 -0.22320459 -0.11905019 -0.12233464].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.